apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: devstack
---  
  
  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  namespace: devstack
  labels:
    app: nodeapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeserver
        image: 111249026938.dkr.ecr.us-west-2.amazonaws.com/devopsrepo01:latest
        ports:
        - containerPort: 3000


---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  namespace: devstack
spec:
  selector:
    app: nodeapp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
