---
- hosts: aws_ec2
  remote_user: ec2-user
  gather_facts: yes
  become: yes
  vars:
    - version: tomcat-10.1.17
  tasks:
    - name: install java
      yum:
        name: java
        state: latest
    - name: download pkg
      get_url:
         url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.17/bin/apache-tomcat-10.1.17.tar.gz
         dest: /usr/local
         mode: 0755
         validate_certs: false
    - name: extracting tomcat file
      unarchive:
         src: /usr/local/apache-tomcat-10.1.17.tar.gz
         dest: /usr/local
         remote_src: yes
    - name: copy the war file
      copy:
         src: /home/jenkins-slave/workspace/Test_build-7/target/simple-app-3.0.0-SNAPSHOT.war
         dest: /usr/local/apache-tomcat-10.1.17/webapps
    - name: start tomcat service
      shell: nohup /usr/local/apache-tomcat-10.1.17/bin/startup.sh
